--SECCION 1
--SELECT, DISTINCT, ORDER BY
SELECT * FROM COUNTRY ORDER BY COUNTRY ASC;-- ORDENANDO LOS PAISES DE FORMA ASCENDENTE.
SELECT * FROM COUNTRY ORDER BY COUNTRY DESC;-- ORDENANDO LOS PAISES DE FORMA DESCENDENTE.