--COUNT, SUM, AVG, MIN, MAX

--MAX = BUSCAR EL MAXIMO
--MIN = BUSCAR EL MINIMO
--AVG = BUSCAR EL PROMEDIO
--SUM = HACER SUMATORIA
--COUNT = HACER UN CONTEO DE ELEMENTOS


--COUNT
SELECT COUNT (RENTAL_ID) FROM RENTAL;
SELECT COUNT(AMOUNT), AMOUNT FROM PAYMENT GROUP BY AMOUNT ORDER BY AMOUNT ASC;
SELECT COUNT(FIRST_NAME), FIRST_NAME FROM ACTOR GROUP BY FIRST_NAME;
--MAX
SELECT MAX(AMOUNT) FROM PAYMENT;
--MIN
SELECT MIN(AMOUNT) FROM PAYMENT;

