--GROUP BY
SELECT COUNT(*), LAST_NAME FROM ACTOR GROUP BY LAST_NAME;
/
SELECT
    C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME, SUM(PA.AMOUNT)
FROM
    PAYMENT PA
JOIN
    CUSTOMER C
ON
    PA.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME
ORDER BY C.CUSTOMER_ID ASC;
/
SELECT * FROM CUSTOMER;
SELECT * FROM PAYMENT;
/
SELECT MAX(RENTAL_DATE) FROM RENTAL;