--Cursores
    --ATRIBUTOS DE LOS CURSORES
    
SQL%ISOPEN-- NO APLICA PARA LOS IMPLICITOS
SQL%FOUND
SQL%NOTFOUND
SQL%ROWCOUNT

--EXPLICITOS



--IMPLICITOS
    --SE GENERAN AUTOMATICO
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = 60;
--Ejemplo de Curso Implicito
SET SERVEROUTPUT ON;
BEGIN
Update TEST
Set C2='MAYTHE LOPEZ' WHERE C2 = 'JUAN';

DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);--NOS DICE LA CANTIDAD DE FILAS AFECTADAS

IF SQL%FOUND THEN
    DBMS_OUTPUT.PUT_LINE('REGISTRO ENCOTRADO');
END IF;

IF SQL%NOTFOUND THEN
    DBMS_OUTPUT.PUT_LINE('REGISTRO NO FUE ENCOTRADO');
END IF;
END;
