--AND, OR, NOT
SELECT * FROM COUNTRY;
/
--AND(SE DEBEN CUMPLIR AMBAS CONDICIONES)
SELECT * FROM COUNTRY WHERE COUNTRY = 'ALGERIA' AND COUNTRY_ID = 12;--NO DA INFORMACION PORQUE LA CONDICION AND NO SE CUMPLE.
SELECT * FROM COUNTRY WHERE COUNTRY = 'ALGERIA' AND COUNTRY_ID = 2;--SI CUMPLE CON AMBAS CONDICIONES.
/
--OR(SE DEBE DE CUMPLIR AL MENOS UNA)
SELECT * FROM COUNTRY WHERE COUNTRY = 'ALGERIA' OR COUNTRY_ID = 12;--MUESTRA DOS REGISTROS PORQUE UNO SI CUMPLE CON LA CONDICION DEL NOMBRE Y OTRO CON EL ID
/
--NOT(PARA EXCLUIR DE LA BUSQUEDA)
SELECT * FROM CATEGORY WHERE NOT NAME = 'Action';--MUESTRA TODAS LAS CATEGORIAS MENOS LA QUE LE INDICAMOS NOT.
SELECT * FROM CATEGORY WHERE NOT NAME = 'Games' AND NOT NAME = 'Horror';--EXCLUYE DE LOS RESULTADOS LOS NOMBRES INDICADOS.
/
--EJERCICIOS
SELECT * FROM PAYMENT WHERE CUSTOMER_ID = 36 AND AMOUNT > 0.99 AND STAFF_ID = 1;
/
SELECT * FROM RENTAL WHERE NOT STAFF_ID = 1 AND CUSTOMER_ID > 250 AND INVENTORY_ID < 100;