--IN
--PARECIDO A LA CONDICION AND, SE PUEDE COMBINAR CON EL NOT
SELECT * FROM CITY WHERE CITY IN ('Chiayi', 'Dongying', 'Fukuyama', 'Kilis');--SOLO ME TRAE LAS CIUDADES INDICADAS.
SELECT * FROM CITY WHERE CITY NOT IN ('Chiayi', 'Dongying', 'Fukuyama', 'Kilis');--ME TRAE TODO EXCEPTO LAS CIUDADES INDICADAS.