--LIKE
--PARA BUSCAR PATRONES DE TEXTO
--A%  QUE EMPIEZECE CON X LETRA
--%A  QUE TERMINE CON X LETRA
--%A% QUE CONTENGA X LETRA
--A%E QUE EMPIECE CON A Y TERMINE CON E
SELECT * FROM FILM WHERE RELEASE_YEAR = 2006 AND TITLE LIKE 'ALI%';
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE 'B%N';--BUSCAR EL PRIMER NOMBRE QUE EMPIECE CON B Y TERMINE CON N